export const ROUTES = {
  home: "/dashboard",
  focus: "/focus",
  session: "/session",
  lock: "/lock",
  locked: "/locked",
  stats: "/stats",
  unlocks: "/unlocks",
  appearance: "/appearance",
  setup: "/setup",
  integrations: "/integrations",
  profile: "/profile",
  subscription: "/account/subscription",
  settings: "/account/settings",
  schedule: "/schedule",
  planner: "/planner",
  intro: "/intro",
  friends: "/friends",
  sprite: "/sprite",
  quiz: "/quiz",
} as const;
