export const ROUTES = {
  home: "/dashboard",
  focus: "/focus",
  session: "/session",
  lock: "/lock",
  stats: "/stats",
  unlocks: "/unlocks",
  appearance: "/appearance",
  setup: "/setup",
  profile: "/profile",
  motivation: "/motivation",
  schedule: "/schedule",
  sprite: "/sprite",
  quiz: "/quiz",
} as const;
