export const SPARK_TINTS = [
  {
    id: "mint",
    name: "Mint spark",
    cost: 0,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#B8FFF3",
    mid: "#7AF0DC",
    lo: "#5EEAD4",
  },
  {
    id: "rose",
    name: "Rose spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFE4F1",
    mid: "#F9A8D4",
    lo: "#F472B6",
  },
  {
    id: "peach",
    name: "Peach spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFE8D6",
    mid: "#FDBA74",
    lo: "#FB923C",
  },
  {
    id: "lemon",
    name: "Lemon spark",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FEF9C3",
    mid: "#FDE047",
    lo: "#EAB308",
  },
  {
    id: "gold",
    name: "Gold spark",
    cost: 16,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFF4B8",
    mid: "#F5D76A",
    lo: "#D4A017",
  },
  {
    id: "sky",
    name: "Sky spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#DBEAFE",
    mid: "#60A5FA",
    lo: "#3B82F6",
  },
  {
    id: "forest",
    name: "Forest spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#D1FAE5",
    mid: "#34D399",
    lo: "#059669",
  },
  {
    id: "lilac",
    name: "Lilac spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#EDE9FE",
    mid: "#C4B5FD",
    lo: "#A78BFA",
  },
  {
    id: "grape",
    name: "Grape spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#E0E7FF",
    mid: "#818CF8",
    lo: "#4F46E5",
  },
  {
    id: "ember",
    name: "Ember spark",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFEDD5",
    mid: "#FB7185",
    lo: "#E11D48",
  },
  {
    id: "ink",
    name: "Ink spark",
    cost: 16,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#E4E4E7",
    mid: "#71717A",
    lo: "#3F3F46",
  },
  {
    id: "sunset",
    name: "Sunset wash",
    cost: 18,
    collection: "starter" as const,
    kind: "gradient" as const,
    hi: "#FDBA74",
    mid: "#FB7185",
    lo: "#E879F9",
  },
  {
    id: "ocean",
    name: "Ocean wash",
    cost: 18,
    collection: "starter" as const,
    kind: "gradient" as const,
    hi: "#5EEAD4",
    mid: "#38BDF8",
    lo: "#2563EB",
  },
  {
    id: "twilight",
    name: "Twilight wash",
    cost: 18,
    collection: "starter" as const,
    kind: "gradient" as const,
    hi: "#C4B5FD",
    mid: "#818CF8",
    lo: "#1D4ED8",
  },
  {
    id: "honey",
    name: "Honey wash",
    cost: 16,
    collection: "starter" as const,
    kind: "gradient" as const,
    hi: "#FDE68A",
    mid: "#FBBF24",
    lo: "#F97316",
  },
  {
    id: "blossom",
    name: "Blossom wash",
    cost: 16,
    collection: "starter" as const,
    kind: "gradient" as const,
    hi: "#F9A8D4",
    mid: "#E9D5FF",
    lo: "#A78BFA",
  },
  {
    id: "aurora",
    name: "Aurora spark",
    cost: 90,
    collection: "aurora" as const,
    kind: "gradient" as const,
    hi: "#E9D5FF",
    mid: "#5EEAD4",
    lo: "#A78BFA",
  },
] as const;

export type SparkTintId = (typeof SPARK_TINTS)[number]["id"];

export function getSparkTint(id: SparkTintId) {
  return SPARK_TINTS.find((row) => row.id === id) ?? SPARK_TINTS[0];
}
