export type SparkAuraId = (typeof SPARK_AURAS)[number]["id"];

export const SPARK_AURAS = [
  {
    id: "none",
    name: "No glow",
    cost: 0,
    collection: "starter" as const,
    blurb: "No body glow.",
    glow: "transparent",
    glowB: null as string | null,
  },
  {
    id: "mint",
    name: "Mint-teal",
    cost: 0,
    collection: "starter" as const,
    blurb: "Mint-teal body glow. Free starter from the study quiz.",
    glow: "#5EEAD4",
    glowB: "#2DD4BF",
  },
  {
    id: "amber",
    name: "Amber",
    cost: 0,
    collection: "starter" as const,
    blurb: "Amber sunset glow. Free starter from the study quiz.",
    glow: "#FBBF24",
    glowB: "#F97316",
  },
  {
    id: "pearl",
    name: "Pearl",
    cost: 0,
    collection: "starter" as const,
    blurb: "Pearl pink and lavender. Free starter from the study quiz.",
    glow: "#FBCFE8",
    glowB: "#C4B5FD",
  },
  {
    id: "grove",
    name: "Grove",
    cost: 0,
    collection: "starter" as const,
    blurb: "Gold and pale green. Free starter from the study quiz.",
    glow: "#FDE68A",
    glowB: "#86EFAC",
  },
  {
    id: "magenta",
    name: "Magenta",
    cost: 0,
    collection: "starter" as const,
    blurb: "Magenta and violet. Free starter from the study quiz.",
    glow: "#E879F9",
    glowB: "#A78BFA",
  },
  {
    id: "hotpink",
    name: "Hot pink",
    cost: 0,
    collection: "starter" as const,
    blurb: "Hot pink glow. Free starter from the study quiz.",
    glow: "#F472B6",
    glowB: "#FB7185",
  },
  {
    id: "lavender",
    name: "Lavender",
    cost: 24,
    collection: "starter" as const,
    blurb: "Lavender body glow.",
    glow: "#A78BFA",
    glowB: null,
  },
  {
    id: "pink",
    name: "Pink",
    cost: 24,
    collection: "starter" as const,
    blurb: "Pink body glow.",
    glow: "#F9A8D4",
    glowB: null,
  },
  {
    id: "gold",
    name: "Gold",
    cost: 40,
    collection: "gold" as const,
    blurb: "Gold body glow.",
    glow: "#E8C547",
    glowB: null,
  },
  {
    id: "aurora",
    name: "Aurora",
    cost: 80,
    collection: "aurora" as const,
    blurb: "Mint and violet body glow.",
    glow: "#5EEAD4",
    glowB: "#A78BFA",
  },
] as const;

export function getSparkAura(id: SparkAuraId) {
  return SPARK_AURAS.find((row) => row.id === id) ?? SPARK_AURAS[0];
}
