export const SPARK_TINTS = [
  {
    id: "mint",
    name: "Natural",
    cost: 0,
    collection: "starter" as const,
    kind: "solid" as const,
    blurb: "Natural species fur. Mint glow is Dragon and brand only.",
    hi: "#FFF4E5",
    mid: "#E07A2F",
    lo: "#B45316",
  },
  {
    id: "rose",
    name: "Rose sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFE4F1",
    mid: "#F9A8D4",
    lo: "#F472B6",
  },
  {
    id: "peach",
    name: "Peach sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFE8D6",
    mid: "#FDBA74",
    lo: "#FB923C",
  },
  {
    id: "lemon",
    name: "Lemon sprite",
    cost: 10,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FEF9C3",
    mid: "#FDE047",
    lo: "#EAB308",
  },
  {
    id: "gold",
    name: "Gold sprite",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    blurb: "Metallic gold with a shine, not lemon.",
    hi: "#FFF8D0",
    mid: "#F0C14A",
    lo: "#B8860B",
  },
  {
    id: "sky",
    name: "Sky sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#DBEAFE",
    mid: "#60A5FA",
    lo: "#3B82F6",
  },
  {
    id: "forest",
    name: "Forest sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#D1FAE5",
    mid: "#34D399",
    lo: "#059669",
  },
  {
    id: "lilac",
    name: "Lilac sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#EDE9FE",
    mid: "#C4B5FD",
    lo: "#A78BFA",
  },
  {
    id: "grape",
    name: "Grape sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#E0E7FF",
    mid: "#818CF8",
    lo: "#4F46E5",
  },
  {
    id: "ember",
    name: "Ember sprite",
    cost: 12,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#FFEDD5",
    mid: "#FB7185",
    lo: "#E11D48",
  },
  {
    id: "ink",
    name: "Ink sprite",
    cost: 14,
    collection: "starter" as const,
    kind: "solid" as const,
    hi: "#E4E4E7",
    mid: "#71717A",
    lo: "#3F3F46",
  },
  {
    id: "sunset",
    name: "Sunset wash",
    cost: 44,
    collection: "starter" as const,
    kind: "gradient" as const,
    blurb: "Premium two-tone. Costs more than a solid.",
    hi: "#FDBA74",
    mid: "#FB7185",
    lo: "#E879F9",
  },
  {
    id: "ocean",
    name: "Ocean wash",
    cost: 44,
    collection: "starter" as const,
    kind: "gradient" as const,
    blurb: "Premium two-tone. Costs more than a solid.",
    hi: "#5EEAD4",
    mid: "#38BDF8",
    lo: "#2563EB",
  },
  {
    id: "twilight",
    name: "Twilight wash",
    cost: 44,
    collection: "starter" as const,
    kind: "gradient" as const,
    blurb: "Premium two-tone. Costs more than a solid.",
    hi: "#C4B5FD",
    mid: "#818CF8",
    lo: "#1D4ED8",
  },
  {
    id: "honey",
    name: "Honey wash",
    cost: 40,
    collection: "starter" as const,
    kind: "gradient" as const,
    blurb: "Premium two-tone. Costs more than a solid.",
    hi: "#FDE68A",
    mid: "#FBBF24",
    lo: "#F97316",
  },
  {
    id: "blossom",
    name: "Blossom wash",
    cost: 40,
    collection: "starter" as const,
    kind: "gradient" as const,
    blurb: "Premium two-tone. Costs more than a solid.",
    hi: "#F9A8D4",
    mid: "#E9D5FF",
    lo: "#A78BFA",
  },
  {
    id: "aurora",
    name: "Aurora sprite",
    cost: 90,
    collection: "aurora" as const,
    kind: "gradient" as const,
    blurb: "Premium mint-violet wash.",
    hi: "#E9D5FF",
    mid: "#5EEAD4",
    lo: "#A78BFA",
  },
  {
    id: "cosmic",
    name: "Cosmic sprite",
    cost: 48,
    collection: "starter" as const,
    kind: "gradient" as const,
    blurb: "Dark blue, lighter blue, and stars.",
    hi: "#93C5FD",
    mid: "#2563EB",
    lo: "#1E3A8A",
  },
] as const;

export type SparkTintId = (typeof SPARK_TINTS)[number]["id"];

export function getSparkTint(id: SparkTintId) {
  return SPARK_TINTS.find((row) => row.id === id) ?? SPARK_TINTS[0];
}
